version: '3.8'

services:

  acne_service:
    image: hollwopelw/project-acne_service:latest
    # build:
    #   context: ./backend_ai/acne
    container_name: acne_service
    ports:
      - "8001:8001"
    networks:
      - ai_network

  wrinkle_service:
    image: hollwopelw/project-wrinkle_service:latest
    # build:
    #   context: ./backend_ai/wrinkle
    container_name: wrinkle_service
    ports:
      - "8002:8002"
    networks:
      - ai_network

  darkspot_service:
    image: hollwopelw/project-darkspot_service:latest
    # build:
    #   context: ./backend_ai/darkspot
    container_name: darkspot_service
    ports:
      - "8003:8003"
    networks:
      - ai_network

  backend_api:
    image: hollwopelw/project-backend_api:latest
    # build:
    #   context: ./backend_api
    container_name: backend_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:pass123@mongo:27017
      SECRET_KEY: admin_s3cret_key
    depends_on:
      - mongo
    networks:
      - ai_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongo_data:/data/db
    networks:
      - ai_network

  frontend:
    image: hollwopelw/project-frontend:latest
    # build:
    #   context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend_api
    networks:
      - ai_network

networks:
  ai_network:

volumes:
  mongo_data:
