version: '3.8'

services:
  backend_api:
    # tty: true
    # stdin_open: true

    build:
      context: ./backend_api
    container_name: backend_api
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:pass123@mongo:27017
      SECRET_KEY: admin_s3cret_key
    depends_on:
      - mongo
    networks:
      - ai_network
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
    volumes:
      - mongo_data:/data/db
    networks:
      - ai_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # NGINX chạy cổng 80 nội bộ, ánh xạ ra ngoài là 3000
    depends_on:
      - backend_api
    networks:
      - ai_network

networks:
  ai_network:
volumes:
  mongo_data:
